name: Code Quality

on:
    workflow_dispatch: ~

jobs:
    sonarqube:
        name: SonarQube
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  ref: ${{ github.sha }}
                  fetch-depth: 0
            - name: SonarCloud Scan
              uses: SonarSource/sonarqube-scan-action@v6
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}